// Generates ToolDesc / ParamDesc via OpenAI instead of the template in toolgen.mjs.
// One request per tool (Chat Completions, response_format: json_object), so
// the model sees the whole tool (name, entity, all parameters) at once and
// the descriptions stay consistent with each other.

const ENDPOINT = 'https://api.openai.com/v1/chat/completions';

const SYSTEM_PROMPT =
  'You are an expert at designing tools for AI agents. You are given ' +
  'technical context for a tool, taken from SAP OData $metadata (service ' +
  'name, EntitySet, HTTP method, fields) - this is ONLY a source of ' +
  'knowledge about what the tool does, NOT content that should end up in ' +
  'the description.\n\n' +
  'ToolDesc must focus exclusively on the business function: what action ' +
  'it performs and what data it returns, from the point of view of the ' +
  'agent deciding when to use this tool - not on where the data technically ' +
  'comes from. NEVER mention in ToolDesc or ParamDesc the name of the ' +
  'OData service, the words "OData"/"API", the EntitySet name, or the HTTP ' +
  'method - that is noise, not information. Write as if the tool could be ' +
  'backed by any data source.\n\n' +
  'Bad:  "Retrieves business partner details from the API_BUSINESS_PARTNER OData service."\n' +
  'Good: "Retrieves core details of a business partner, such as name and category."\n\n' +
  'Descriptions are in English, factual, with no marketing language, at ' +
  'most 1-2 sentences for ToolDesc and half a sentence for ParamDesc (what ' +
  'the parameter represents from a business point of view, not its data ' +
  'type). Reply ONLY with valid JSON in the format ' +
  '{"ToolDesc": "...", "params": {"<ParamName>": "..."}}, with no extra text.';

function buildUserPrompt(tool) {
  const paramLines = tool.to_Parameters
    .map((p) => `  - ${p.ParamName} (SAP: ${p.ODataProperty}, usage: ${p.ParamUsage}, type: ${p.ParamType})`)
    .join('\n');

  return [
    '(The context below is internal background knowledge - do not quote it in the descriptions.)',
    `ToolName: ${tool.ToolName}`,
    `SAP OData service: ${tool.ServiceName}`,
    `EntitySet: ${tool.EntitySet}${tool.NavigationProp ? ` (navigation: ${tool.NavigationProp})` : ''}`,
    `HTTP method: ${tool.HTTPMethod}`,
    tool.SelectFields ? `Selected fields: ${tool.SelectFields}` : '',
    'Parameters:',
    paramLines || '  (none)',
    '',
    'Write a ToolDesc describing the tool\'s business function, and a ' +
      'ParamDesc for each parameter in the list above - both with no ' +
      'technical references to OData/service/EntitySet/HTTP.',
  ].filter(Boolean).join('\n');
}

/**
 * @param {object} tool payload generated by toolgen.mjs (with template descriptions)
 * @param {{apiKey:string, model:string}} cfg
 * @returns {Promise<{ToolDesc:string, params:Record<string,string>}>}
 */
export async function describeTool(tool, cfg) {
  const res = await fetch(ENDPOINT, {
    method: 'POST',
    headers: {
      authorization: `Bearer ${cfg.apiKey}`,
      'content-type': 'application/json',
    },
    body: JSON.stringify({
      model: cfg.model,
      temperature: 0.2,
      response_format: { type: 'json_object' },
      messages: [
        { role: 'system', content: SYSTEM_PROMPT },
        { role: 'user', content: buildUserPrompt(tool) },
      ],
    }),
  });

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`OpenAI returned HTTP ${res.status} for ${tool.ToolName}\n${body.slice(0, 500)}`);
  }

  const data = await res.json();
  const content = data.choices?.[0]?.message?.content;
  if (!content) throw new Error(`OpenAI returned no content for ${tool.ToolName}`);

  let parsed;
  try {
    parsed = JSON.parse(content);
  } catch (err) {
    throw new Error(`OpenAI returned invalid JSON for ${tool.ToolName}: ${err.message}\n${content.slice(0, 500)}`);
  }

  return { ToolDesc: parsed.ToolDesc ?? '', params: parsed.params ?? {} };
}

/**
 * Overwrites tools' ToolDesc/ParamDesc with results from OpenAI, on a copy.
 * Runs sequentially (not in parallel) - keeps the progress log readable and
 * avoids hitting rate limits with a larger number of tools.
 */
export async function enrichWithOpenAI(tools, cfg, limits) {
  const cut = (s, max) => (s.length <= max ? s : s.slice(0, max));
  const out = [];

  for (const [i, tool] of tools.entries()) {
    process.stdout.write(`  [${String(i + 1).padStart(3)}/${tools.length}] ${tool.ToolName} ... `);
    try {
      const { ToolDesc, params } = await describeTool(tool, cfg);
      out.push({
        ...tool,
        ToolDesc: cut(ToolDesc || tool.ToolDesc, limits.toolDesc),
        to_Parameters: tool.to_Parameters.map((p) => ({
          ...p,
          ParamDesc: cut(params[p.ParamName] || p.ParamDesc, limits.paramDesc),
        })),
      });
      console.log('OK');
    } catch (err) {
      console.log(`SKIPPED (${err.message})`);
      out.push(tool); // keep the template description from toolgen.mjs
    }
  }

  return out;
}
